### ISSUE TITLE
XF 2.3.3 customs pins disappear

### ISSUE THREAD

**Issue by xalikoutis** [TorbenK/TK.CustomMap#147]
Today XF 2.3.3 was released in the stable channel. After upgrading my project custompins are not visible

**Comment by JeanCollas** [comment]
That is weird, I don't see any update on Xamarin.Forms.Maps recently (actually more or less none)

https://github.com/xamarin/Xamarin.Forms/tree/master/Xamarin.Forms.Maps

Are you sure you haven't changed anything else?

**Comment by xalikoutis** [comment]
ok i ll write down a test project to reproduce it

**Comment by TorbenK** [comment]
2.3.3. was release on 16.09.

**Comment by JeanCollas** [comment]
Just asking, I haven't done the update yet, but I am wondering why it wouldn't work anymore as nothing has changed ;)

**Comment by kikolopes90** [comment]
Before the old version works, this new version no longer works, nor does it run "Release"

Debug:
```
11-30 10:37:39.629 W/DynamiteModule( 1366): Local module descriptor class for com.google.android.gms.googlecertificates not found.
11-30 10:37:39.638 I/DynamiteModule( 1366): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:2
11-30 10:37:39.638 I/DynamiteModule( 1366): Selected remote version of com.google.android.gms.googlecertificates, version >= 2
11-30 10:37:39.639 E/DynamiteModule( 1366): Failed to load DynamiteLoader: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.dynamite.DynamiteModule$DynamiteLoaderClassLoader" on path: DexPathList[[zip file "/data/app/*/base.apk"],nativeLibraryDirectories=[/data/app/*/lib/arm, /data/app/*/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
11-30 10:37:39.639 W/DynamiteModule( 1366): Failed to load remote module: Failed to get module context
11-30 10:37:39.640 W/DynamiteModule( 1366): Failed to load module via fast routetn: Remote load failed. No local fallback found.
11-30 10:37:39.640 W/DynamiteModule( 1366): Local module descriptor class for com.google.android.gms.googlecertificates not found.
11-30 10:37:39.644 I/DynamiteModule( 1366): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:2
11-30 10:37:39.644 I/DynamiteModule( 1366): Selected remote version of com.google.android.gms.googlecertificates, version >= 2
```

Release:
```
Severity Code Description Project File Line Suppression State
Error The "LinkAssemblies" task failed unexpectedly.
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Reference to metadata item 'System.Void Xamarin.Forms.Maps.Android.MapRenderer::OnElementChanged(Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1<Xamarin.Forms.View>)' (defined in 'TK.CustomMap.Android, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null') from 'TK.CustomMap.Android, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null' could not be resolved. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Xamarin.Forms.Maps.Android.MapRenderer::OnElementChanged(Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1<Xamarin.Forms.View>)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   --- End of inner exception stack trace ---
   at Java.Interop.Tools.Diagnostics.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Comment by xalikoutis** [comment]
I unistalled, reinstalled the XF packages form nuget and fixed my problem.
**UPDATE** 
wrong there is a problem indeed, follow the PR
