### ISSUE TITLE
LinkAssemblies failure with TK.CustomMap using skip linking assemblies

### ISSUE THREAD

**Issue by suringr** [TorbenK/TK.CustomMap#210]
this is the error:

 Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'System.Void Xamarin.Forms.Maps.Android.MapRenderer::OnElementChanged(Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1<Xamarin.Forms.View>)' (defined in assembly 'TK.CustomMap.Android, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.Forms.Maps.Android, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Xamarin.Forms.Maps.Android.MapRenderer::OnElementChanged(Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1<Xamarin.Forms.View>)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   --- End of inner exception stack trace ---
   at Java.Interop.Tools.Diagnostics.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Keep.Clients.Droid			

can you help on this issue?

**Comment by TorbenK** [comment]
Which NuGet version/XF version are you using?

**Comment by horacehylee** [comment]
@TorbenK  Same here
```Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Android.Gms.Location.Places.IAutocompletePrediction' (defined in assembly 'TK.CustomMap.Android, Version=1.5.1.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.GooglePlayServices.Location, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Gms.Location.Places.IAutocompletePrediction```

Xamarin.Forms: v2.3.4.231
Xamarin.Forms.Maps: v2.3.4.231
Xamarin.GooglePlayServices.Maps: v42.1001.0

**Comment by rohitvipin** [comment]
Ran in to the issue today. Happening only in release mode.

**Comment by ghost** [comment]
Hi, does anyone have a solution or workaround for this issue? Disabling the Linker functionality is not an option for me.

**Comment by TorbenK** [comment]
Can you try to downgrade to XF 2.3.3 and see if this still happens?

**Comment by rohitvipin** [comment]
It's not related to XF. It's the latest version of XF Maps changing the
reference of base packages. Everything has been split into smaller packages
by Google play.
If you update your referenced XF maps it should start working again.

**Comment by gsaldana** [comment]
Hi
I'm getting this error message:

Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Android.Gms.Location.Places.IAutocompletePrediction' (defined in assembly 'TK.CustomMap.Android, Version=1.5.1.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.GooglePlayServices.Location, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Gms.Location.Places.IAutocompletePrediction
   en Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   en MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   en Mono.Linker.Steps.MarkStep.MarkGenericArguments(IGenericInstance instance)
   en Mono.Linker.Steps.MarkStep.GetOriginalType(TypeReference type)
   en Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   en MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   en Mono.Linker.Steps.MarkStep.MarkField(FieldReference reference)
   en Mono.Linker.Steps.MarkStep.InitializeFields(TypeDefinition type)
   en Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
   en Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
   en Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
   en Mono.Linker.Steps.MarkStep.Initialize()
   en Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   en Mono.Linker.Pipeline.Process(LinkContext context)
   en MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   en Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en Java.Interop.Tools.Diagnostics.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   en Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   en Xamarin.Android.Tasks.LinkAssemblies.Execute()
   en Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   en Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Sales2Go.Droid	

Have anybody found the solution for that?

thanks in advance!!

**Comment by Micnick** [comment]
I have the same error, when I started to generate the release of the project.

Error XA2006: Could not resolve reference to 'Android.Gms.Location.Places.IAutocompletePrediction' (defined in assembly 'TK.CustomMap.Android, Version = 1.5.1.0, Culture = neutral, PublicKeyToken = null') with scope 'Xamarin. GooglePlayServices.Location, Version = 1.0.0.0, Culture = neutral, PublicKeyToken = null '. When the scope is different from the defining assembly, it usually means that the type is forwarded.

**Comment by hot33331** [comment]
Same here: Error		The "LinkAssemblies" task failed unexpectedly.
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Android.Gms.Location.Places.IAutocompletePrediction' (defined in assembly 'TK.CustomMap.Android, Version=1.5.1.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.GooglePlayServices.Location, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Gms.Location.Places.IAutocompletePrediction

**Comment by Micnick** [comment]
Hi @hot33331 

I solved it, downloading the code of the project and adding it to the solution, add and associate the dll directly.

**Comment by garie** [comment]
I have the same error when building in release mode. Based on this [post](https://stackoverflow.com/questions/43327181/xamarin-app-only-compiles-in-debug-mode-not-release-mode-when-using-3rd-party) maybe some of the references need to be updated.

**Comment by BillyMartin1964** [comment]
@Micnick  How does one "add and associate the dll directly" ?

This is my Linker error:

The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Void TK.CustomMap.Droid.TKCustomMapRenderer::OnCameraChange(System.Object,Android.Gms.Maps.GoogleMap/CameraChangeEventArgs)' in assembly: 'TK.CustomMap.Android.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Xamarin.Forms.Maps.Android.MapRenderer::OnCameraChange(Android.Gms.Maps.Model.CameraPosition)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	HunterTracker.Android	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1629

**Comment by walteriousnut** [comment]
Had the same linker issue. Resolved by opening the Droid project properties > Android Options and changing the value for 'Linking' from 'Sdk Assemblies Only' to 'Sdk and User Assemblies'
