### ISSUE TITLE
MissingMethodException: Method 'Xamarin.Forms.Maps.Android.MapRenderer.OnCameraChange' not found.

### ISSUE THREAD

**Issue by kaitlynbrown** [TorbenK/TK.CustomMap#269]
I see the above error any time I try to open a TK.CustomMap. Using Xamarin.Forms.Maps.Map does not result in the same error. Several other people seem to be having the same problem: https://bugzilla.xamarin.com/show_bug.cgi?id=60746

**Comment by InquisitorJax** [comment]
occurs after upgrading to the latest xamarin forms 2.5

**Comment by InquisitorJax** [comment]
here's the changeset from xamarin forms maps changes to the maprenderer
https://github.com/xamarin/Xamarin.Forms/commit/dff6ecd7b55c60f7ff8f6091d422978dbb050cf5#diff-7f7d97ddb08959905b9fa2bc55f233ce

**Comment by TorbenK** [comment]
Should be fixed with 2.0.0-pre1

**Comment by LarsNymand** [comment]
- Upgraded to 2.0.0-pre1
- Removed all Xamarin.Forms.Maps references.
- Added TKGoogleMaps.Init(this, bundle); to Android

I am not getting this (OnCameraChange) exception anymore (unless this new (NullReferenceException) exception is happening before the OnCameraChange exception) after updating to 2.0.0-pre1.

Am I missing something?

Update: The NullReferenceException was because of my binding to a MapRegion property which was null (this was no issue in v1.6.1).
`mapView.SetBinding(TKCustomMap.MapRegionProperty, nameof(MapRegion));`
By setting the MapRegion property to a default location fixed this exception.

It all works for me now. Thank you!

```
Xamarin caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object.
  at TK.CustomMap.Droid.TKCustomMapRenderer.UpdateMapRegion () [0x0003a] in <a8020b0f1856498891c040e965344fc8>:0 
  at TK.CustomMap.Droid.TKCustomMapRenderer.OnMapReady (Android.Gms.Maps.GoogleMap googleMap) [0x00129] in <a8020b0f1856498891c040e965344fc8>:0 
  at Android.Gms.Maps.IOnMapReadyCallbackInvoker.n_OnMapReady_Lcom_google_android_gms_maps_GoogleMap_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_googleMap) [0x00011] in <edd902d5391542adb87c92c0219e00cb>:0 
  at (wrapper dynamic-method) System.Object:5b274806-1bb3-4d17-bd3c-9fb22f285e5b (intptr,intptr,intptr)
	at md532cd08c1e980ede3c944ac07445ae34e.TKCustomMapRenderer.n_onMapReady(Native Method)
	at md532cd08c1e980ede3c944ac07445ae34e.TKCustomMapRenderer.onMapReady(TKCustomMapRenderer.java:75)
	at com.google.android.gms.maps.MapView$zza$1.zza(Unknown Source)
	at com.google.android.gms.maps.internal.zzt$zza.onTransact(Unknown Source)
	at android.os.Binder.transact(Binder.java:507)
	at fv.b(:com.google.android.gms.DynamiteModulesB@11746448:20)
	at com.google.android.gms.maps.internal.bf.a(:com.google.android.gms.DynamiteModulesB@11746448:5)
	at com.google.maps.api.android.lib6.impl.bc.run(:com.google.android.gms.DynamiteModulesB@11746448:5)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by jorgemrht** [comment]
I have the same problem with the version 1.6.1, but if I upgrade the new version (2.0) I need update all the project. 

So, Is it possible to have both versions (1.6.1 and 2.0)? In my case I have some problem with the new version in iOS but in android is work fine ...
