### ISSUE TITLE
2.0.0-pre3 - Clustering Support

### ISSUE THREAD

**Issue by TorbenK** [TorbenK/TK.CustomMap#272]
I just released[ 2.0.0-pre2](https://www.nuget.org/packages/TK.CustomMap/2.0.0-pre2). Give it a try!

Release notes:

- **Added clustering support**
- Added padding parameter to FitMapRegionToPositions and FitToMapRegions
- Removed dependency on Xamarin.Forms.Maps
- Renamed CustomPins to Pins
- Removed property name constants
- MapCenter is now read-only

Probably more but I forgot ...

**Comment by LarsNymand** [comment]
I am getting below exception when calling `await Navigation.PopModalAsync();`

Any ideas?

```
Xamarin caused by: android.runtime.JavaProxyThrowable: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Android.Gms.Maps.MapView'.
  at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <7cfbebb561c54efc9010b018c0846c7e>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <7cfbebb561c54efc9010b018c0846c7e>:0 
  at Android.Views.View.set_OnFocusChangeListener (Android.Views.View+IOnFocusChangeListener value) [0x00036] in <2cbc8bc37f564147a10de1abb0c4e399>:0 
  at Xamarin.Forms.Platform.Android.ViewRenderer`2[TView,TNativeView].Dispose (System.Boolean disposing) [0x0002c] in <b5b1173f4d49442b898c45e26ae39e48>:0 
  at TK.CustomMap.Droid.TKCustomMapRenderer.Dispose (System.Boolean disposing) [0x0013e] in <a8020b0f1856498891c040e965344fc8>:0 
  at Java.Lang.Object.Dispose () [0x00000] in <2cbc8bc37f564147a10de1abb0c4e399>:0 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) [0x0007b] in <b5b1173f4d49442b898c45e26ae39e48>:0 
  at Java.Lang.Object.Dispose () [0x00000] in <2cbc8bc37f564147a10de1abb0c4e399>:0 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) [0x0007b] in <b5b1173f4d49442b898c45e26ae39e48>:0 
  at Java.Lang.Object.Dispose () [0x00000] in <2cbc8bc37f564147a10de1abb0c4e399>:0 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) [0x0007b] in <b5b1173f4d49442b898c45e26ae39e48>:0 
  at Xamarin.Forms.Platform.Android.PageRenderer.Dispose (System.Boolean disposing) [0x00011] in <b5b1173f4d49442b898c45e26ae39e48>:0 
  at Java.Lang.Object.Dispose () [0x00000] in <2cbc8bc37f564147a10de1abb0c4e399>:0 
  at Xamarin.Forms.Platform.Android.Platform+<>c__DisplayClass47_0.<Xamarin.Forms.INavigation.PopModalAsync>b__0 (Android.Animation.Animator a) [0x00010] in <b5b1173f4d49442b898c45e26ae39e48>:0 
  at Xamarin.Forms.Platform.Android.GenericAnimatorListener.OnAnimationEnd (Android.Animation.Animator animation) [0x0000e] in <b5b1173f4d49442b898c45e26ae39e48>:0 
  at Android.Animation.AnimatorListenerAdapter.n_OnAnimationEnd_Landroid_animation_Animator_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_animation) [0x0000f] in <2cbc8bc37f564147a10de1abb0c4e399>:0 
  at (wrapper dynamic-method) System.Object:22a53cf7-3f60-4f79-8ff0-2df17d27aa07 (intptr,intptr,intptr)
	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.GenericAnimatorListener.n_onAnimationEnd(Native Method)
	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.GenericAnimatorListener.onAnimationEnd(GenericAnimatorListener.java:40)
	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1121)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1149)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1309)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:925)
	at android.view.Choreographer.doCallbacks(Choreographer.java:702)
	at android.view.Choreographer.doFrame(Choreographer.java:635)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by InquisitorJax** [comment]
1) there a reason MapCenter has become readonly - used to use it with binding to set map location. What's the alternative?
2) get the same error as above after view is closed.
3) most of the time the map is just black (doesn't load the map tiles)

I have a sample project [here](https://github.com/InquisitorJax/Xamarin-Forms-Maps) (TK map on location selection page , XForms Map on main page)

**Comment by TorbenK** [comment]
I will look at the errors asap. Thanks for the sample project.

Regarding `MapCenter`, use `MapRegion` instead.

**Comment by TorbenK** [comment]
@InquisitorJax 

The disposing issue should be fixed next pre release. 

About 3: this is probably an issue with your app using multiple instances of `MapView`. I already posted that some time ago [here](https://forums.xamarin.com/discussion/comment/181471/#Comment_181471). Android has `MapFragment` to handle multiple map instances in a single activity, but Xamarin.Forms does not support Fragments afaik.

**Comment by LarsNymand** [comment]
Dispose now works in pre2 thanks!

**Comment by InquisitorJax** [comment]
I can also confirm that the dispose now works.
 wrt 3: I found that if I don't show the map in a modal view, then the map shows up just fine.
I'll see if I can log a bug with xamarin on the issue.
EDIT: Scratch that - it seems sometimes it just works, but  most of the time the second map renders black :| 
Still a Xamarin Forms Map issue though.

EDIT2: Seems like the "black map" issue is only in the emulator. Run on device works just fine.

**Comment by InquisitorJax** [comment]
trying to call FitMapRegionToPostions causes nullreference exception.
See TKMapView.cs in linked example.
Could it be that the code is firing too early (map hasn't rendered yet)?

**Comment by TorbenK** [comment]
It should not raise a NullReferenceException though. 

There is a `MapReady` event/command.

**Comment by TorbenK** [comment]
If there are no more concerns, I will move 2.0.0 to stable at the beginning of next week.

**Comment by backlashs** [comment]
The UWP Files don't seem to be getting downloaded as part of the 2.0.0 nuget package,
Is this correct?

**Comment by GrumpyMan** [comment]
I get this when clicking on a cluster marker. 2.0.0-pre3

12-06 21:22:37.318 I/MonoDroid( 7634): UNHANDLED EXCEPTION:
12-06 21:22:37.398 I/MonoDroid( 7634): System.NullReferenceException: Object reference not set to an instance of an object.
12-06 21:22:37.398 I/MonoDroid( 7634):   at TK.CustomMap.Droid.TKCustomMapRenderer+<>c__DisplayClass36_0.<OnMarkerClick>b__0 (System.Collections.Generic.KeyValuePair`2[TKey,TValue] i) [0x0000c] in <4ca3da68f3024c3fbd2be902081d17d0>:0 
12-06 21:22:37.398 I/MonoDroid( 7634):   at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0002c] in <b5bd9d990a0b4733885e90ca5ec6c0fb>:0 
12-06 21:22:37.398 I/MonoDroid( 7634):   at TK.CustomMap.Droid.TKCustomMapRenderer.OnMarkerClick (System.Object sender, Android.Gms.Maps.GoogleMap+MarkerClickEventArgs e) [0x00016] in <4ca3da68f3024c3fbd2be902081d17d0>:0 
12-06 21:22:37.398 I/MonoDroid( 7634):   at Android.Gms.Maps.GoogleMap+IOnMarkerClickListenerImplementor.OnMarkerClick (Android.Gms.Maps.Model.Marker marker) [0x00017] in <edd902d5391542adb87c92c0219e00cb>:0 
12-06 21:22:37.398 I/MonoDroid( 7634):   at Android.Gms.Maps.GoogleMap+IOnMarkerClickListenerInvoker.n_OnMarkerClick_Lcom_google_android_gms_maps_model_Marker_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_marker) [0x00011] in <edd902d5391542adb87c92c0219e00cb>:0 
12-06 21:22:37.399 I/MonoDroid( 7634):   at (wrapper dynamic-method) System.Object:4666f2c0-b95f-487d-86dc-c22ef8df1081 (intptr,intptr,intptr)

**Comment by vincentcastagna** [comment]
Wow, did not see that awesome post. I'm gonna give it a try next week, and I'll give you a complete feedBack on that @TorbenK  . Thanks for your support.

**Comment by jycribbs** [comment]
Any word on when 2.0.0 will be moved to stable?  Also, I too am getting the NRE when clicking a pin.

**Comment by vincentcastagna** [comment]
Alright. Tested, and got it work.
Clustering is working well, the only thing that does not work are images for Pins (when clustering set to true) and click on cluster that crashes app but only sometimes.

**Update** : 
- There is one problem for me with the mapCenter ... that was a great feature to use, as I'm working on an uber app like, and was adding the pin at mapCenter Latitude and Longitude. I tried to manage it with mapRegion.Center.Latitude & Longitude but it does not work as expected.*
- There might also be a bug when adding a circle. It does not show on the map (seems that the setter is not called).

Great idea to get rid of XF Maps dependency.

Nice update @TorbenK , thanks

**Comment by Depechie** [comment]
Using MapRegion to position the map needs a radius.
How do you move the region of the map keep the current zoom level ( radius )? Everything for this is now hidden or read only, like  getting VisibleRegion or setting MapCenter.

**Comment by jycribbs** [comment]
I created a Distance property called ZoomLevel in my viewmodel, and whenever I call MoveToMapRegion, I pass the property.  If the user zooms the map out, I update the property as needed.

**Comment by Depechie** [comment]
Ha didn't check if there were zoom events available to interact with that... so in those you do get the actual zoom factor?

**Comment by jycribbs** [comment]
After looking at my code, it seems I only manually update the ZoomLevel when the user clicks the “zoom out to see the whole country” button, or the “zoom into my location” button.  In both cases, I know what zoom level to use, so setting the property is easy.

If the user drags the map around, then I don’t need to bother with zoom level.
