### ISSUE TITLE
Android - IllegalStateException newLatLngBounds

### ISSUE THREAD

**Issue by CliffCawley** [TorbenK/TK.CustomMap#35]
I just had this occur on a device that a tester was using. Not sure yet on reproduction steps but thought I'd report anyway:

**Message:**

```
Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occured for the map view. Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions.
```

**Stack Trace:**

```
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x9444ef70 + 0x00024> in <filename unknown>:0 
  at Android.Runtime.JNIEnv.CallVoidMethod (IntPtr jobject, IntPtr jmethod, Android.Runtime.JValue* parms) <0x9d7d9578 + 0x000bf> in <filename unknown>:0 
  at Android.Gms.Maps.GoogleMap.AnimateCamera (Android.Gms.Maps.CameraUpdate update) <0x9444e080 + 0x00137> in <filename unknown>:0 
  at TK.CustomMap.Droid.TKCustomMapRenderer.FitMapRegionToPositions (IEnumerable`1 positions, Boolean animate) <0x9444c4a8 + 0x00123> in <filename unknown>:0 
  at TK.CustomMap.TKCustomMap.FitMapRegionToPositions (IEnumerable`1 positions, Boolean animate) <0x9444c2c0 + 0x0003b> in <filename unknown>:0 
  at SkeduloMobile.ViewTimelineAndNavigationModel.<HackMapRecenter>m__5 () <0x93acb9d8 + 0x000db> in <filename unknown>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () <0xae975748 + 0x0003f> in <filename unknown>:0 
  at Java.Lang.IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) <0xae9756a0 + 0x0003f> in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:ad80dd52-4761-44bc-bbc3-51ba0b2d2fde (intptr,intptr)
  --- End of managed exception stack trace ---
java.lang.IllegalStateException: Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occured for the map view.  Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions.
    at com.google.a.a.ae.b(Unknown Source)
    at com.google.maps.api.android.lib6.gmm6.c.a.a(Unknown Source)
    at com.google.maps.api.android.lib6.e.dy.a(Unknown Source)
    at com.google.maps.api.android.lib6.gmm6.c.a.a(Unknown Source)
    at com.google.maps.api.android.lib6.e.ev.b(Unknown Source)
    at com.google.android.gms.maps.internal.j.onTransact(SourceFile:92)
    at android.os.Binder.transact(Binder.java:395)
    at com.google.android.gms.maps.internal.IGoogleMapDelegate$zza$zza.animateCamera(Unknown Source)
    at com.google.android.gms.maps.GoogleMap.animateCamera(Unknown Source)
    at mono.java.lang.RunnableImplementor.n_run(Native Method)
    at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6862)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by TorbenK** [comment]
Thanks for the report. Seems like you calling `FitMapRegionToPositions` before the map has his bounds. Probably want to do this in the `Appearing` event of the page or `PinsReadyCommand` of the map.

**Comment by CliffCawley** [comment]
Ah right, I've switched to FitToMapRegions anyway and I just call it in RouteCalculationFinishedCommand with

```
if (Route.All(i => i.IsCalculated))
                {
                    mapView.FitToMapRegions(Route.Select(i => i.Bounds), true);
                }
```

**Comment by TorbenK** [comment]
Great. I close this then.
