### ISSUE TITLE
No constructor found for Xamarin.Forms.Maps.Android.MapRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)

### ISSUE THREAD

**Issue by MauSamba** [TorbenK/TK.CustomMap#42]
Hi,

I'm getting this error when I show a page with a map, then pop that page and push another page with a map; it sems a silent error(no crash)
StackTrace

at Java.Interop.TypeManager.CreateInstance (IntPtr handle, JniHandleOwnership transfer, System.Type targetType) [0x001a4] in <filename unknown>:0 
  at Java.Lang.Object.GetObject (IntPtr handle, JniHandleOwnership transfer, System.Type type) [0x000e5] in <filename unknown>:0 
  at Java.Lang.Object._GetObject[T](IntPtr handle, JniHandleOwnership transfer) [0x0001a] in <filename unknown>:0 
  at Java.Lang.Object.GetObject[T](IntPtr handle, JniHandleOwnership transfer) [0x00000] in <filename unknown>:0 
  at Java.Lang.Object.GetObject[T](IntPtr jnienv, IntPtr handle, JniHandleOwnership transfer) [0x00006] in <filename unknown>:0 
  at Android.Gms.Maps.GoogleMap+IOnCameraChangeListenerInvoker.n_OnCameraChange_Lcom_google_android_gms_maps_model_CameraPosition_ (IntPtr jnienv, IntPtr native__this, IntPtr native_position) [0x00000] in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:bac3a343-82f3-41c1-a6fd-bbc2b9e5c348 (intptr,intptr,intptr)
System.MissingMethodExceptionNo constructor found for Xamarin.Forms.Maps.Android.MapRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)
  at Java.Interop.TypeManager.CreateProxy (System.Type type, IntPtr handle, JniHandleOwnership transfer) [0x00058] in <filename unknown>:0 
  at Java.Interop.TypeManager.CreateInstance (IntPtr handle, JniHandleOwnership transfer, System.Type targetType) [0x0012c] in <filename unknown>:0 
Java.Lang.ErrorException of type 'Java.Interop.JavaLocationException' was thrown.
Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.

  --- End of managed exception stack trace ---
java.lang.Error: Java callstack:
    at md5d956392b2b421ac2c9ccfc063253dcd9.MapRenderer.n_onCameraChange(Native Method)
    at md5d956392b2b421ac2c9ccfc063253dcd9.MapRenderer.onCameraChange(MapRenderer.java:54)
    at com.google.android.gms.maps.GoogleMap$7.onCameraChange(Unknown Source)
    at com.google.android.gms.maps.internal.zze$zza.onTransact(Unknown Source)
    at android.os.Binder.transact(Binder.java:386)
    at com.google.android.gms.maps.internal.aa.a(SourceFile:93)
    at com.google.maps.api.android.lib6.gmm6.c.a.a(Unknown Source)
    at com.google.maps.api.android.lib6.gmm6.c.b.run(Unknown Source)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5539)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by TorbenK** [comment]
I don't think this is related to the control - closed.
