### ISSUE TITLE
Android - java.net.UnknownHostException

### ISSUE THREAD

**Issue by CliffCawley** [TorbenK/TK.CustomMap#72]
So if you're offline or in flight mode you get this crash and it'll take down your app.

To reproduce, go offline, then start an app that uses TK.CustomMap on Android

```
java.net.UnknownHostException: Unable to resolve host "maps.googleapis.com": No address associated with hostname
    at java.net.InetAddress.lookupHostByName(InetAddress.java:427)
    at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
    at java.net.InetAddress.getAllByName(InetAddress.java:215)
    at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
    at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:224)
    at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:193)
    at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:113)
    at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:344)
    at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:329)
    at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
    at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
    at com.squareup.okhttp.Call.getResponse(Call.java:271)
    at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
    at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
    at com.squareup.okhttp.Call.access$100(Call.java:34)
    at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
    at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker
```

**Comment by TorbenK** [comment]
Thanks again for reporting Cliff.

**Comment by TorbenK** [comment]
1.5.1.
